### ISSUE TITLE
How do i use this..?

### ISSUE THREAD

**Issue by TheRealFame** [timoschwarzer/godot-audio-haptics#5]
Hello! I am using godot 4.3.

I found the addon while scrolling the asset library! And since I also have a ps5 controller. I decided to try getting this functionality working!

But.. 

I don't know how to make this kinda file work with godot, And why godot can see it's path and files. But not add it to the plugin's list.

**Comment by timoschwarzer** [comment]
This addon is a GDExtension. Read more about these in general here: https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/index.html

How to use this addon is outlined in the readme.

**Comment by TheRealFame** [comment]
Yeah that didn't really fix the issue..

**Comment by timoschwarzer** [comment]
Then please describe your issue more specifically so I can try to help you. You install plugins by putting them into the addons directory in your project.

**Comment by TheRealFame** [comment]
> Then please describe your issue more specifically so I can try to help you. You install plugins by putting them into the addons directory in your project.

I put the gdextention into my add-ons folder, Keeping it's folder structure. And it seemingly didn't load, And it wasn't detected as an addon or anything. I'll probably have to reimport it into an empty project..

**Comment by timoschwarzer** [comment]
How did you check that it did not load? Is there absolutely no related output in the editor console? What system are you on?

**Comment by TheRealFame** [comment]
> How did you check that it did not load? Is there absolutely no related output in the editor console? What system are you on?

The only thing that happened was, Once I added the addon, It did this. But didn't get picked up or give me any options related to it.

  Attempt to register extension class 'AudioEffectControllerHaptics', which appears to be already registered.
  Attempt to register extension class 'AudioEffectControllerHapticsInstance', which appears to be already registered.

I am using Linux, With the flatpak version of 4.3 mono

**Comment by timoschwarzer** [comment]
Did you check whether the audio bus effect exists as described in the readme in this repository?

**Comment by TheRealFame** [comment]
> Did you check whether the audio bus effect exists as described in the readme in this repository?

Yep, It's not there/non existent, Atleast from where I'm checking 

(The audio dock)

**Comment by timoschwarzer** [comment]
Can you show a screenshot of the audio effect menu?

**Comment by TheRealFame** [comment]
> Can you show a screenshot of the audio effect menu?

It's working as of now! I got the audio bus connected, Only thing I'm confused about is the error here- 

W 0:00:00:0436   AudioEffectControllerHapticsInstance: Did not find a compatible Audio Haptics device
  <C++ Source>   /home/runner/work/godot-audio-haptics/godot-audio-haptics/src/AudioEffectControllerHapticsInstance.cpp:110 @ AudioEffectControllerHapticsInstance()

Here are two screenshot's as well
![image](https://github.com/user-attachments/assets/19d85a67-0585-4a20-bec1-9c8eaaf073bc)
![image](https://github.com/user-attachments/assets/f044a702-77c6-4a72-8b72-df557baadfa4)

**Comment by timoschwarzer** [comment]
Is your DualSense Controller connected and if yes, how?

**Comment by TheRealFame** [comment]
> Is your DualSense Controller connected and if yes, how?

Not at the moment connected, So I guess I now understand why that debugger code pop's in.. Thanks!
